/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package unoesc.edu.br;

import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author D3nys
 */
public class LISTAswimg06 extends javax.swing.JFrame {
    Vector<String>List = new Vector<>();
    Vector<String>Listpar = new Vector<>();
    Vector<String>ListImpar = new Vector<>();
    Vector<String>Listlimpa = new Vector<>();

        int Inicio ;
        int Fim ;
        int Acumulado = 0;
    
    
    /**
     * Creates new form LISTAswimg06
     */
    public LISTAswimg06() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbINICIO = new javax.swing.JLabel();
        jLbFIM = new javax.swing.JLabel();
        jLbVALORES = new javax.swing.JLabel();
        jTFInicio = new javax.swing.JTextField();
        jTFFim = new javax.swing.JTextField();
        jLbListaValores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLLIsta = new javax.swing.JList();
        jLbTotal = new javax.swing.JLabel();
        jLbResposta = new javax.swing.JLabel();
        jBTCalcular = new javax.swing.JButton();
        jCBTipo = new javax.swing.JComboBox();
        jBReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLbINICIO.setText("Inicio :");

        jLbFIM.setText("Fim :");

        jLbVALORES.setText("Tipo de Valores :");

        jTFFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFFimActionPerformed(evt);
            }
        });

        jLbListaValores.setText("Lista de Valores :");

        jScrollPane1.setViewportView(jLLIsta);

        jLbTotal.setText("Resultado :");

        jLbResposta.setText("...");

        jBTCalcular.setText("Calcular");
        jBTCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTCalcularActionPerformed(evt);
            }
        });

        jCBTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Par", "Impar" }));

        jBReset.setText("Reset");
        jBReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbVALORES)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLbListaValores)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbTotal)
                        .addGap(18, 18, 18)
                        .addComponent(jLbResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLbFIM)
                            .addGap(18, 18, 18)
                            .addComponent(jTFFim))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLbINICIO)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jBTCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBReset)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbINICIO)
                    .addComponent(jTFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbFIM)
                    .addComponent(jTFFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbVALORES)
                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLbListaValores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbTotal)
                    .addComponent(jLbResposta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBReset)
                    .addComponent(jBTCalcular))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFimActionPerformed

    private void jBTCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTCalcularActionPerformed
/*1) Tela Exemplos List. O usuário informa o valor de início, um valor final e o tipo de
valor (par ou impar) do JComboBox. O botão Calcula fará a soma dos números
(pares ou impares) existentes no intervalo informado pelo usuário e mostrará cada
número no JList (lista de valores).*/
       int aux;
        String inicio = jTFInicio.getText();
        String fim = jTFFim.getText();
    //   Vector<String>Listpar = new Vector<>(); ira aparecer uma ves so
   // Vector<String>ListImpar = new Vector<>();  ira aparecer um a lista so

        int Inicio = Integer.parseInt(inicio);
        int Fim = Integer.parseInt(fim);
        int Acumulado = 0;
       if (Inicio > Fim){
           JOptionPane.showMessageDialog(null, "Seu Burro e ao contrario");
           aux = Inicio;
           Inicio = Fim;
           Fim = aux;
       }
        
        if (jCBTipo.getSelectedIndex() == 0){
        for (int i = Inicio+1; i <= Fim; i++) {
            if (i % 2 == 0) {
                String x = String.valueOf(i);
                   Listpar.add(x);
                    Acumulado += i;
                   }
        }
        } 
    if (jCBTipo.getSelectedIndex() == 1){
        for (int i = Inicio+1; i <= Fim; i++) {
            if (i % 2 == 1) {
                String x = String.valueOf(i);
                     ListImpar.add(x);
                    Acumulado += i;
                    
                    
                }
            }
        }
    if (jCBTipo.getSelectedIndex()==0){
        jLLIsta.setListData(Listpar);
    }else{
        jLLIsta.setListData(ListImpar);
    }

        String Resposta = String.valueOf(Acumulado);
        jLbResposta.setText(Resposta);
        
    
           
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTCalcularActionPerformed

    private void jBResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResetActionPerformed

       
          
                   ListImpar.removeAll(ListImpar);
                   Listpar.removeAll(Listpar);            
                
         if (jCBTipo.getSelectedIndex()==0){
        jLLIsta.setListData(Listlimpa);
    }else{
        jLLIsta.setListData(Listlimpa);
    }

        String Resposta = String.valueOf(Acumulado);
        jLbResposta.setText(Resposta);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jBResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LISTAswimg06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LISTAswimg06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LISTAswimg06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LISTAswimg06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LISTAswimg06().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBReset;
    private javax.swing.JButton jBTCalcular;
    private javax.swing.JComboBox jCBTipo;
    private javax.swing.JList jLLIsta;
    private javax.swing.JLabel jLbFIM;
    private javax.swing.JLabel jLbINICIO;
    private javax.swing.JLabel jLbListaValores;
    private javax.swing.JLabel jLbResposta;
    private javax.swing.JLabel jLbTotal;
    private javax.swing.JLabel jLbVALORES;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFFim;
    private javax.swing.JTextField jTFInicio;
    // End of variables declaration//GEN-END:variables
}
