/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Eduardo
 */
public class Argamassa extends javax.swing.JFrame {

    /**
     * Creates new form Argamassa
     */
    public Argamassa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlbMtApartamento = new javax.swing.JLabel();
        jTFTamanhoM2 = new javax.swing.JTextField();
        jlbDimenssao = new javax.swing.JLabel();
        jlbComprimento = new javax.swing.JLabel();
        jTFComprimento1 = new javax.swing.JTextField();
        jlbAltura = new javax.swing.JLabel();
        jTFAltura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRB2mm = new javax.swing.JRadioButton();
        jRB3mm = new javax.swing.JRadioButton();
        jRB4mm = new javax.swing.JRadioButton();
        jRB5mm = new javax.swing.JRadioButton();
        jRB7mm = new javax.swing.JRadioButton();
        jRB8mm = new javax.swing.JRadioButton();
        jRB10mm = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRBEpoxil = new javax.swing.JRadioButton();
        jRBFlexivel = new javax.swing.JRadioButton();
        jRBFluido = new javax.swing.JRadioButton();
        jRBRejunteSobRejunte = new javax.swing.JRadioButton();
        jRBFachadas = new javax.swing.JRadioButton();
        jRBPedraRustica = new javax.swing.JRadioButton();
        jRBPscina = new javax.swing.JRadioButton();
        jRBPorcelana = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jlbx = new javax.swing.JLabel();
        jTFComprimento2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLbComsumoRejunte = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbMtApartamento.setText("MT² Apartamento:");

        jTFTamanhoM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTamanhoM2ActionPerformed(evt);
            }
        });

        jlbDimenssao.setText("Dimensão de Cerâmica");

        jlbComprimento.setText("Comprimento (cm) :");

        jlbAltura.setText("Altura (mm):");

        jLabel6.setText("Espessura de Juntas:");

        jRB2mm.setText("2 mm");

        jRB3mm.setText("3 mm");

        jRB4mm.setText("4 mm");

        jRB5mm.setText("5 mm");
        jRB5mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB5mmActionPerformed(evt);
            }
        });

        jRB7mm.setText("7 mm");
        jRB7mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB7mmActionPerformed(evt);
            }
        });

        jRB8mm.setText("8 mm");
        jRB8mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB8mmActionPerformed(evt);
            }
        });

        jRB10mm.setText("10 mm");

        jLabel7.setText("Tipo de Rejunte:");

        buttonGroup1.add(jRBEpoxil);
        jRBEpoxil.setText("Epoxil");

        buttonGroup1.add(jRBFlexivel);
        jRBFlexivel.setText("Flexivel");

        buttonGroup1.add(jRBFluido);
        jRBFluido.setText("Fluido");

        buttonGroup1.add(jRBRejunteSobRejunte);
        jRBRejunteSobRejunte.setText("Rejunte sob Rejunte");

        buttonGroup1.add(jRBFachadas);
        jRBFachadas.setText("Fachadas");

        buttonGroup1.add(jRBPedraRustica);
        jRBPedraRustica.setText("Pedra Rustica");

        buttonGroup1.add(jRBPscina);
        jRBPscina.setText("Pscina");

        buttonGroup1.add(jRBPorcelana);
        jRBPorcelana.setText("Porcelana");

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlbx.setText("x");

        jLabel9.setText("Consumo Estimado de Rejunte:");

        jLbComsumoRejunte.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRB2mm)
                    .addComponent(jRB3mm)
                    .addComponent(jRB4mm)
                    .addComponent(jRB5mm)
                    .addComponent(jRB7mm)
                    .addComponent(jRB8mm)
                    .addComponent(jRB10mm)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlbDimenssao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlbComprimento)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTFComprimento1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jlbx, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRBEpoxil)
                                            .addComponent(jRBFlexivel)
                                            .addComponent(jRBFluido)
                                            .addComponent(jRBRejunteSobRejunte)
                                            .addComponent(jRBFachadas)
                                            .addComponent(jRBPedraRustica)
                                            .addComponent(jRBPscina)
                                            .addComponent(jRBPorcelana)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFComprimento2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlbAltura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbMtApartamento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFTamanhoM2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLbComsumoRejunte, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMtApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTamanhoM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jlbDimenssao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbComprimento)
                    .addComponent(jTFComprimento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbx, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFComprimento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbAltura)
                    .addComponent(jTFAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB2mm)
                    .addComponent(jRBEpoxil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB3mm)
                    .addComponent(jRBFlexivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB4mm)
                    .addComponent(jRBFluido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB5mm)
                    .addComponent(jRBRejunteSobRejunte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB7mm)
                    .addComponent(jRBFachadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB8mm)
                    .addComponent(jRBPedraRustica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB10mm)
                    .addComponent(jRBPscina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBPorcelana)
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLbComsumoRejunte))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFTamanhoM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTamanhoM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTamanhoM2ActionPerformed

    private void jRB5mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB5mmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB5mmActionPerformed

    private void jRB7mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB7mmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB7mmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//pegar imformcao da parte grafica
        String Tamanho = jTFTamanhoM2.getText();
        String A = jTFComprimento1.getText();
        String B = jTFComprimento2.getText();
        String Altura = jTFAltura.getText();
        //trasformar em float
        float t = Float.parseFloat(Tamanho);
         float a = Float.parseFloat(A);
         float b = Float.parseFloat(B);
         float c = Float.parseFloat(Altura);
         float d = 0;
         float cr= 0;
         //escolher Rejunte
         if(jRB2mm.isSelected() ){
             d = (float) 0.02;
         }
         if(jRB3mm.isSelected()){
             d= (float) 0.03;
         }
        if(jRB4mm.isSelected()){
            d = (float) 0.04;
        }
        if (jRB5mm.isSelected()){
            d = (float) 0.05;
        }
        if( jRB7mm.isSelected()){
            d = (float) 0.07;
         }
        if (jRB8mm.isSelected()){
            d = (float) 0.08;
        }
        if(jRB10mm.isSelected()){
            d = (float) 0.10;
        }
        // calcular tipo de coeficiente
        if(jRBEpoxil.isSelected()){
            cr = (float) 1.58;
        }
        if(jRBFlexivel.isSelected()){
            cr = (float) 1.75;
        }
        if(jRBFluido.isSelected()){
            cr = (float) 1.49;
        }
        if(jRBRejunteSobRejunte.isSelected()){
            cr = (float) 1.32;
        }
        if(jRBFachadas.isSelected()){
            cr = (float) 1.76;
        }
        if(jRBPedraRustica.isSelected()){
            cr = (float) 1.62;
        }
        if(jRBPorcelana.isSelected()){
            cr = (float) 1.62;
        }
        
        
        float ConsumoDeReajunte = ((a+b)*c*d*cr)/(a+b);
        float Rea = ConsumoDeReajunte * t;
        String rea = String.valueOf(Rea);
        String comsuReajunte =  String.valueOf(ConsumoDeReajunte);      
        jLbComsumoRejunte.setText(rea);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRB8mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB8mmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB8mmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Argamassa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Argamassa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Argamassa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Argamassa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Argamassa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbComsumoRejunte;
    private javax.swing.JRadioButton jRB10mm;
    private javax.swing.JRadioButton jRB2mm;
    private javax.swing.JRadioButton jRB3mm;
    private javax.swing.JRadioButton jRB4mm;
    private javax.swing.JRadioButton jRB5mm;
    private javax.swing.JRadioButton jRB7mm;
    private javax.swing.JRadioButton jRB8mm;
    private javax.swing.JRadioButton jRBEpoxil;
    private javax.swing.JRadioButton jRBFachadas;
    private javax.swing.JRadioButton jRBFlexivel;
    private javax.swing.JRadioButton jRBFluido;
    private javax.swing.JRadioButton jRBPedraRustica;
    private javax.swing.JRadioButton jRBPorcelana;
    private javax.swing.JRadioButton jRBPscina;
    private javax.swing.JRadioButton jRBRejunteSobRejunte;
    private javax.swing.JTextField jTFAltura;
    private javax.swing.JTextField jTFComprimento1;
    private javax.swing.JTextField jTFComprimento2;
    private javax.swing.JTextField jTFTamanhoM2;
    private javax.swing.JLabel jlbAltura;
    private javax.swing.JLabel jlbComprimento;
    private javax.swing.JLabel jlbDimenssao;
    private javax.swing.JLabel jlbMtApartamento;
    private javax.swing.JLabel jlbx;
    // End of variables declaration//GEN-END:variables
}
